[bumpversion]
current_version = 0.0.2

[mypy-huey,huey.*]
ignore_missing_imports = True

[mypy-django,django.*]
ignore_missing_imports = True

[mypy-pytest,pytest.*]
ignore_missing_imports = True

[mypy-testfixtures]
ignore_missing_imports = True

[tool:pytest]
# DJANGO_SETTINGS_MODULE=django_app.settings

[flake8]
max_line_length = 99

[tox]
envlist = py3{7,8,9}-ci
install_command=pip install --index-url=https://artifactory.allegrogroup.com/artifactory/api/pypi/group-python/simple -U {opts} {packages}

[gh-actions]
python =
  3.7: py38-ci
  3.8: py38-ci
  3.9: py39-ci


[pytest]
DJANGO_SETTINGS_MODULE=django_app.settings

[testenv]
deps =
    -r {toxinidir}/requirements/test.txt
    dev: -r {toxinidir}/requirements/dev.txt
    -r {toxinidir}/tests/django_app/requirements.txt
    -r {toxinidir}/tests/flask_app/requirements.txt
usedevelop = True
commands = 
    py.test --junit-xml=./tests-results/report-{envname}-$(uuidgen).xml --tb=native \
            --cov=logextractx --cov-report=html --cov-report=term-missing --no-cov-on-fail \
            --cov-fail-under=100 --cov-branch \
            logextractx tests/flask_app tests/django_app

